language: html
language: php

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  project_name: Port Royale 3 Offline Map
  on:
    branch: master